SELECT INFO.FOOD_TYPE, INFO.REST_ID, INFO.REST_NAME, INFO.FAVORITES

FROM REST_INFO INFO
JOIN
(
    SELECT FOOD_TYPE, MAX(FAVORITES) AS TOP_RATED
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) BEST_REST 
ON INFO.FOOD_TYPE = BEST_REST.FOOD_TYPE AND INFO.FAVORITES = BEST_REST.TOP_RATED

ORDER BY INFO.FOOD_TYPE DESC