SELECT DATE_FORMAT(RES.SALES_DATE,'%Y-%m-%d'), RES.PRODUCT_ID, RES.USER_ID, RES.SALES_AMOUNT
FROM
(
    SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
    FROM ONLINE_SALE
    UNION ALL
    SELECT SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
    FROM OFFLINE_SALE
) RES

WHERE YEAR(RES.SALES_DATE) = '2022' AND MONTH(RES.SALES_DATE) = '03'
ORDER BY RES.SALES_DATE, RES.PRODUCT_ID ASC, USER_ID ASC