SET @joinedUsers_2021 = (SELECT COUNT(USER_ID) FROM USER_INFO WHERE YEAR(JOINED) = '2021');

SELECT
    YEAR(SALES_DATE) AS 'YEAR',
    MONTH(SALES_DATE) AS 'MONTH',
    COUNT(DISTINCT(I.USER_ID)) AS 'PUCHASED_USERS',
    ROUND(COUNT(DISTINCT(I.USER_ID)) / @joinedUsers_2021, 1) AS 'PUCHASED_RATIO'
    
FROM USER_INFO I
    LEFT JOIN ONLINE_SALE S ON I.USER_ID = S.USER_ID
    
WHERE
    YEAR(JOINED) = '2021' AND
    SALES_DATE IS NOT NULL

GROUP BY SUBSTRING(SALES_DATE, 1, 7)
ORDER BY YEAR ASC, MONTH ASC