SELECT
    FH.FLAVOR
FROM FIRST_HALF FH
    JOIN (
        SELECT
            FLAVOR,
            SUM(TOTAL_ORDER) AS 'SUM_OF_ORDER'
        FROM JULY
        GROUP BY FLAVOR
    ) J ON FH.FLAVOR = J.FLAVOR

GROUP BY FH.FLAVOR
ORDER BY SUM(FH.TOTAL_ORDER + J.SUM_OF_ORDER) DESC
LIMIT 3