WITH BEST_REVIEWER AS
(
    SELECT MEMBER_ID
    FROM REST_REVIEW
    
    GROUP BY MEMBER_ID
    ORDER BY COUNT(REVIEW_ID) DESC
    LIMIT 1
)

SELECT
    MEMBER_NAME,
    RR.REVIEW_TEXT,
    DATE_FORMAT(RR.REVIEW_DATE, '%Y-%m-%d') AS 'REVIEW_DATE'
FROM REST_REVIEW RR
    JOIN MEMBER_PROFILE MP ON RR.MEMBER_ID = MP.MEMBER_ID
    LEFT JOIN BEST_REVIEWER BR ON RR.MEMBER_ID = BR.MEMBER_ID
    
WHERE BR.MEMBER_ID IS NOT NULL

ORDER BY RR.REVIEW_DATE ASC, RR.REVIEW_TEXT ASC