SELECT
    BD.TITLE,
    BD.BOARD_ID,
    RP.REPLY_ID,
    RP.WRITER_ID,
    RP.CONTENTS,
    DATE_FORMAT(RP.CREATED_DATE, '%Y-%m-%d') AS 'CREATED_DATE'
    
FROM USED_GOODS_BOARD BD
    JOIN USED_GOODS_REPLY RP ON BD.BOARD_ID = RP.BOARD_ID
    
WHERE YEAR(BD.CREATED_DATE) = '2022' AND MONTH(BD.CREATED_DATE) = '10'

ORDER BY RP.CREATED_DATE ASC, BD.TITLE ASC