SELECT
    HISTORY_ID,
    ROUND(DAILY_FEE * (DATEDIFF(H.END_DATE, H.START_DATE) + 1) * ((100 - IFNULL(DISCOUNT_RATE, 0)) / 100), 0) AS 'FEE'
    
FROM CAR_RENTAL_COMPANY_CAR RT
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON RT.CAR_ID = H.CAR_ID
    LEFT JOIN (
        SELECT CAR_TYPE, DURATION_TYPE, DISCOUNT_RATE
        FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
        ORDER BY DURATION_TYPE DESC
    ) DC ON RT.CAR_TYPE = DC.CAR_TYPE AND (DATEDIFF(H.END_DATE, H.START_DATE) + 1) >= DC.DURATION_TYPE

WHERE RT.CAR_TYPE = '트럭'

GROUP BY HISTORY_ID
ORDER BY FEE DESC, HISTORY_ID DESC